"""empty message

Revision ID: 622c8141ed60
Revises: b6fd93d64bb4
Create Date: 2022-04-13 19:37:05.462534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622c8141ed60'
down_revision = 'b6fd93d64bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
